name: Mirror to GitLab
on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # full history

      - name: Set up git
        run: |
          git config user.name "mirror-bot"
          git config user.email "mirror-bot@users.noreply.github.com"

      - name: Push to GitLab
        env:
          GITLAB_PROJECT: ${{ secrets.GITLAB_PROJECT }}
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          git remote add gitlab "https://oauth2:${GITLAB_TOKEN}@gitlab.com/${GITLAB_PROJECT}.git"
          # Push branches and tags (avoids hidden GitHub refs that GitLab rejects)
          git push --prune --all gitlab
          git push --prune --tags gitlab

