name: Sync to GitLab & Deploy Pages

on:
  push:
    branches: [ "main" ]   # change if your default branch isn't main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to GitLab mirror
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
          GITLAB_PATH: hubblesetup/hubble    # <namespace>/<project>
          GITLAB_BRANCH: main                # change if needed
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Add remote (idempotent)
          git remote remove gitlab 2>/dev/null || true
          git remote add gitlab "https://oauth2:${GITLAB_TOKEN}@gitlab.com/${GITLAB_PATH}.git"

          # Push current commit to the target branch on GitLab
          git push --force --follow-tags gitlab HEAD:${GITLAB_BRANCH}
